### ISSUE TITLE
`imageset.sh` script should not delete old AMIs until the script finishes successfully

### ISSUE THREAD

**Issue by matt-boris** [taskcluster/community-tc-config#607]
There are some times where the image building process hangs up (I've only ever seen this happen on AWS) and it errors out before fully creating the new AMIs, while also deleting the old ones. This causes a backlog of worker pool errors because of non-existent AMIs.

**Comment by lotas** [comment]
I would probably extend this issue to not only defer deletion, but also keep a history of last X images (similar to what you can do in kubernetes with deployments, where you can keep history to quickly rollback to the previous working one)
And as we've seen, keeping at least 1 more is necessary in case new one doesn't work
