### ISSUE TITLE
Task users on Windows have PATH which includes administrator user folders

### ISSUE THREAD

**Issue by petemoore** [taskcluster/community-tc-config#757]
@jschwartzentruber reported in [matrix](https://matrix.to/#/!whDRjjSmICCgrhFHsQ:mozilla.org/$FckOTwEJ_-7x6-im2rY14_9dGXTpwxc2pzcnzdOBJU0?via=mozilla.org&via=matrix.org&via=ungleich.ch) that an administrator user folder (`C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps`) is included in the path of a task user.

This was due to a bug in the bootstrap script here: https://github.com/taskcluster/community-tc-config/blob/e07e1e6e5fd39597350d6669833194a455e30934/imagesets/generic-worker-win2022/bootstrap.ps1#L153

which is setting the Machine path (i.e. for all users) to include the `PATH` environment variable of the current (administrative) user.

Instead, this code should append entries to the current Machine `PATH` environment variable.

**Comment by lotas** [comment]
I've already reported both issues in #751 but hopefully this fix could close both
