### ISSUE TITLE
Error unmarshaling generic worker config: unknown field "statelessHostname"

### ISSUE THREAD

**Issue by jschwartzentruber** [taskcluster/community-tc-config#777]
https://community-tc.services.mozilla.com/worker-manager/proj-fuzzing%2Fgrizzly-reduce-worker/errors contains lots of errors like this:

```
Error loading configuration, args: [], root cause: Error unmarshaling generic worker config file /etc/generic-worker/config as JSON: json: unknown field "statelessHostname", exit code: 64
```

Is this related to the Ubuntu 24.04 update? I don't see anything about statelessHostname in the fuzzing.yml config.

**Comment by jschwartzentruber** [comment]
cc @petemoore

**Comment by petemoore** [comment]
That looks like the worker pool config contains docker-worker config, but it is a generic-worker pool.

**Comment by jschwartzentruber** [comment]
Oops. This pool is deployed from community-tc-config.

**Comment by petemoore** [comment]
Ah, the secret https://community-tc.services.mozilla.com/secrets/worker-pool%3Aproj-fuzzing%2Fgrizzly-reduce-worker needs to be deleted. I'm not sure how to handle this best automatically. It is secret config which is required for docker-worker, but when we migrate to generic-worker, that secret doesn't get automatically deleted. I'll manually delete it for now, and that will fix the issue.

**Comment by petemoore** [comment]
`taskcluster api secrets remove worker-pool:proj-fuzzing/grizzly-reduce-worker` seems to have fixed it.
