### ISSUE TITLE
interactive username gdm does not match task user task_xxx from file "/next-task-user.json"

### ISSUE THREAD

**Issue by jschwartzentruber** [taskcluster/community-tc-config#783]
This is a frequent worker error currently being seen in eg. [proj-fuzzing/decision](https://community-tc.services.mozilla.com/worker-manager/proj-fuzzing%2Fdecision/errors) pool since the ubuntu 24.04 update.

**Comment by jschwartzentruber** [comment]
Probably #784 and #785 are caused by this.

**Comment by matt-boris** [comment]
Closing now, as I think this has been resolved 👍🏻 Please reopen if you see again.
