### ISSUE TITLE
number of gnome session users is not exactly one - not sure which user is interactively logged on: []string{""}

### ISSUE THREAD

**Issue by jschwartzentruber** [taskcluster/community-tc-config#784]
This is a frequent worker error currently being seen in eg. [proj-fuzzing/decision](https://community-tc.services.mozilla.com/worker-manager/proj-fuzzing%2Fdecision/errors) pool since the ubuntu 24.04 update.

**Comment by matt-boris** [comment]
Should be fixed in https://github.com/taskcluster/taskcluster/pull/7215. We can reopen if we see this occur some more after rolling out this update to the pools.
