### ISSUE TITLE
could not determine interactive username: number of gnome session users is not exactly one - not sure which user is interactively logged on: []string{""}

### ISSUE THREAD

**Issue by jschwartzentruber** [taskcluster/community-tc-config#785]
This is a frequent worker error currently being seen in eg. [proj-fuzzing/decision](https://community-tc.services.mozilla.com/worker-manager/proj-fuzzing%2Fdecision/errors) pool since the ubuntu 24.04 update.

Could be the same issue as #784

**Comment by petemoore** [comment]
This is Generic Worker bug taskcluster/taskcluster#7012. 😬 
I'll close here, but we'll try to work on a fix in the taskcluster repo.
