### ISSUE TITLE
MicrosoftEdgeUpdate.exe process running on fuzzing images

### ISSUE THREAD

**Issue by tysmith** [taskcluster/community-tc-config#884]
This is unnecessary and triggered a failure on a fuzzing instance.

@pyoor pointed out this can be disabled via:
```
sc config edgeupdate start=disabled
sc config edgeupdatem start=disabled
```

**Comment by matt-boris** [comment]
Fixed in https://github.com/taskcluster/community-tc-config/pull/885.

**Comment by petemoore** [comment]
Thanks Boris!
